catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  min-document@<=2.19.0: '>=2.19.1'
  semver: '7.7.3'
  vite: '7.2.7'

shellEmulator: true

trustPolicy: no-downgrade

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'
  - '@anolilab/*'
