onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  chrono-node@<2.2.4: '>=2.2.4'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  jpeg-js@<0.4.0: '>=0.4.0'
  jpeg-js@<0.4.4: '>=0.4.4'
  minimist@<0.2.1: '>=0.2.1'
  minimist@<0.2.4: '>=0.2.4'
  phin@<3.7.1: '>=3.7.1'
  sharp@<0.30.5: '>=0.30.5'
  sharp@<0.32.6: '>=0.32.6'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  xml2js@<0.5.0: '>=0.5.0'
