overrides:
  "@babel/runtime@<7.26.10": ">=7.26.10"
  chrono-node@<2.2.4: ">=2.2.4"
  esbuild@<=0.24.2: ">=0.25.0"
  form-data@<2.5.4: ">=2.5.4"
  jpeg-js@<0.4.0: ">=0.4.0"
  jpeg-js@<0.4.4: ">=0.4.4"
  phin@<3.7.1: ">=3.7.1"
  sharp@<0.30.5: ">=0.30.5"
  sharp@<0.32.6: ">=0.32.6"
  tmp@<=0.2.3: ">=0.2.4"
  tough-cookie@<4.1.3: ">=4.1.3"
  vite@<=5.4.19: ">=5.4.20"
  vite@>=5.0.0 <5.1.8: ">=5.1.8"
  vite@>=5.0.0 <5.4.15: ">=5.4.15"
  vite@>=5.0.0 <5.4.16: ">=5.4.16"
  vite@>=5.0.0 <5.4.17: ">=5.4.17"
  vite@>=5.0.0 <5.4.18: ">=5.4.18"
  vite@>=5.0.0 <=5.1.7: ">=5.1.8"
  vite@>=5.0.0 <=5.4.11: ">=5.4.12"
  vite@>=5.0.0 <=5.4.18: ">=5.4.19"
  vite@>=5.1.0 <=5.1.6: ">=5.1.7"
  xml2js@<0.5.0: ">=0.5.0"
onlyBuiltDependencies:
  - sharp
