catalog:
  '@tailwindcss/postcss': ^4.1.18
  tailwindcss: ^4.1.18

catalogMode: prefer
minimumReleaseAge: 1440

cleanupUnusedCatalogs: true

dedupeInjectedDeps: true

disallowWorkspaceCycles: true

ignoreWorkspaceCycles: false

includeWorkspaceRoot: false

injectWorkspacePackages: false

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - vitest
  - '@vitest/*'
  - typescript
  - '@types/*'
  - '@anolilab/*'
  - '@commitlint/*'

onlyBuiltDependencies:
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  chrono-node@<2.2.4: '>=2.2.4'
  form-data@<2.5.4: '>=2.5.4'
  jpeg-js@<0.4.0: '>=0.4.0'
  jpeg-js@<0.4.4: '>=0.4.4'
  min-document@<=2.19.0: '>=2.19.1'
  minimist@<0.2.1: '>=0.2.1'
  minimist@<0.2.4: '>=0.2.4'
  phin@<3.7.1: '>=3.7.1'
  semver: 7.7.3
  sharp@<0.30.5: '>=0.30.5'
  sharp@<0.32.6: '>=0.32.6'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  vite: 7.2.7
  xml2js@<0.5.0: '>=0.5.0'

preferWorkspacePackages: true

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
    - 'cached-factory@0.1.0'
    - 'undici-types@6.21.0'
    - 'undici@5.29.0'
