catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

overrides:
  "@babel/runtime@<7.26.10": ">=7.26.10"
  chrono-node@<2.2.4: ">=2.2.4"
  cross-spawn@>=7.0.0 <7.0.5: ">=7.0.5"
  esbuild@<=0.24.2: ">=0.25.0"
  form-data@<2.5.4: ">=2.5.4"
  jpeg-js@<0.4.0: ">=0.4.0"
  jpeg-js@<0.4.4: ">=0.4.4"
  micromatch@<4.0.8: ">=4.0.8"
  minimist@<0.2.1: ">=0.2.1"
  minimist@<0.2.4: ">=0.2.4"
  phin@<3.7.1: ">=3.7.1"
  rollup@>=4.0.0 <4.22.4: ">=4.22.4"
  sharp@<0.30.5: ">=0.30.5"
  sharp@<0.32.6: ">=0.32.6"
  tar-fs@>=2.0.0 <2.1.2: ">=2.1.2"
  tar-fs@>=2.0.0 <2.1.3: ">=2.1.3"
  tmp@<=0.2.3: ">=0.2.4"
  tough-cookie@<4.1.3: ">=4.1.3"
  vite@<=5.4.19: ">=5.4.20"
  vite@>=5.0.0 <5.4.15: ">=5.4.15"
  vite@>=5.0.0 <5.4.16: ">=5.4.16"
  vite@>=5.0.0 <5.4.17: ">=5.4.17"
  vite@>=5.0.0 <5.4.18: ">=5.4.18"
  vite@>=5.0.0 <=5.4.11: ">=5.4.12"
  vite@>=5.0.0 <=5.4.18: ">=5.4.19"
  vite@>=5.3.0 <5.3.6: ">=5.3.6"
  vite@>=5.3.0 <=5.3.5: ">=5.3.6"
  xml2js@<0.5.0: ">=0.5.0"
onlyBuiltDependencies:
  - puppeteer
  - sharp
  - unrs-resolver
