name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

permissions:
    contents: "read" # to read the repository
    issues: "write" # for the shared workflow to comment on and label issues
    pull-requests: "write" # for the shared workflow to comment on and label pull requests

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@382cb6ceef0cc355d67ce923e0173ac7d4a9d135" # v24.0.8 # main
        with:
            target-repo: "anolilab/resume"
            onboarding-lead: "prisis"
