name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@a53f7a16f5a2746f28e5407e85ed093103a15aba" # main
        with:
            target-repo: "anolilab/resume"
            onboarding-lead: "prisis"
