name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

permissions:
    contents: "read" # to read the repository
    issues: "write" # for the shared workflow to comment on and label issues
    pull-requests: "write" # for the shared workflow to comment on and label pull requests

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@d403f72a96c4b04c3d93ff1199c0787d544cd000" # v22.0.6 # main
        with:
            target-repo: "anolilab/resume"
            onboarding-lead: "prisis"
