name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@13fa35fefde7f2ad64dbaa108f6421ae3062d711" # v18.0.4 # main
        with:
            target-repo: "anolilab/resume"
