name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@4a32d0dd738ba310135bb4641d405ed46f227a39" # main
        with:
            target-repo: "anolilab/resume"
