name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yaml@802f3b1d00b0ab47c3102b4f4ebd866b9f7f8fcf" # v18.0.3 # main
        with:
            target-repo: "anolilab/resume"
