name: "CI"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
    pull_request:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
            - "!v[0-9]*"

permissions:
    contents: "read"

jobs:
    lint-workflows:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411" # v2.19.4
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            # From https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
            - name: "Check workflow files"
              run: |
                  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
                  ./actionlint -color -shellcheck=""
