name: "CI"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
    pull_request:
        paths:
            - ".github/workflows/**"
        branches:
            - "main"
            - "!v[0-9]*"

permissions:
    contents: "read"

jobs:
    lint-workflows:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176" # v2.17.0
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            # From https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
            - name: "Check workflow files"
              run: |
                  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
                  ./actionlint -color -shellcheck=""
