# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Lint

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - main
    pull_request: # yamllint disable-line rule:empty-values

concurrency:
    group: "ci-lint-${{ github.ref }}-1"
    cancel-in-progress: true

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    files-changed:
        name: Detect what files changed
        runs-on: ubuntu-latest
        timeout-minutes: 3
        # Map a step output to a job output
        outputs:
            frontend_lintable: "${{ steps.changes.outputs.frontend_lintable }}"
            markdown_lintable: "${{ steps.changes.outputs.markdown_lintable }}"
            yaml_lintable: "${{ steps.changes.outputs.yaml_lintable }}"
        steps:
            - name: Git checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
              env:
                  GIT_COMMITTER_NAME: GitHub Actions Shell
                  GIT_AUTHOR_NAME: GitHub Actions Shell
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: Check for file changes
              uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
              id: changes
              with:
                  token: "${{ github.token }}"
                  filters: .github/file-filters.yml

    eslint:
        if: "needs.files-changed.outputs.frontend_lintable == 'true'"
        needs: files-changed
        name: Lint (eslint)
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                  egress-policy: audit

            - name: Git checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: GitHub Actions Shell
                  GIT_AUTHOR_NAME: GitHub Actions Shell
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
              with:
                  version: 8
                  run_install: "false"

            - name: Use Node.js 20.x
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
              with:
                  node-version: 20.x
                  cache: pnpm

            - name: Install packages
              run: pnpm install --frozen-lockfile

            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: pnpm dlx audit-ci@^6 --config ./audit-ci.jsonc --report-type=summary

            - name: lint
              run: "pnpm run lint:eslint"

    yaml-lint:
        if: "needs.files-changed.outputs.yaml_lintable == 'true'"
        needs: files-changed
        name: Lint (yaml)
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                  egress-policy: audit

            - name: Git checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: GitHub Actions Shell
                  GIT_AUTHOR_NAME: GitHub Actions Shell
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: Lint YAML files
              uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
              with:
                  config_file: .yamllint.yaml
                  file_or_dir: .
                  strict: true

    markdown-lint:
        if: "needs.files-changed.outputs.markdown_lintable == 'true'"
        needs: files-changed
        name: Lint (markdown)
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                  egress-policy: audit

            - name: Git checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: GitHub Actions Shell
                  GIT_AUTHOR_NAME: GitHub Actions Shell
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
              with:
                  version: 8
                  run_install: "false"

            - name: Use Node.js 20.x
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
              with:
                  node-version: 20.x
                  cache: pnpm

            - name: Install packages
              run: pnpm install --frozen-lockfile
              env:
                  SKIP_CHECK: "true"

            - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
              run: pnpm dlx audit-ci@^6 --config ./audit-ci.jsonc --report-type=summary

            - name: lint
              run: "pnpm run lint:text"
              continue-on-error: true

            - name: skipping markdown lint for now
              run: exit 0
    # This check runs once all dependant jobs have passed
    # It symbolizes that all required checks have successfully passed (Or skipped)
    # This check is the only required GitHub check
    test-required-check:
        needs: [files-changed, eslint, yaml-lint, markdown-lint] # TODO add "package-json-lint"
        name: Check Lint Run
        # This is necessary since a failed/skipped dependent job would cause this job to be skipped
        if: always()
        runs-on: ubuntu-latest
        steps:
            # If any jobs we depend on fail, we will fail since this is a required check
            # NOTE: A timeout is considered a failure
            - name: Harden Runner
              uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
              with:
                  egress-policy: audit

            - name: Check for failures
              if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
              run: |
                  echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
