name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@a53f7a16f5a2746f28e5407e85ed093103a15aba" # main
        with:
            target-repo: "anolilab/resume"
