name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"

permissions:
    contents: "read"
    discussions: "write"
    issues: "write"
    pull-requests: "write"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@382cb6ceef0cc355d67ce923e0173ac7d4a9d135" # v24.0.8 # main
        with:
            target-repo: "anolilab/resume"
