name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@4a32d0dd738ba310135bb4641d405ed46f227a39" # main
        with:
            target-repo: "anolilab/resume"
