name: "Scorecards supply-chain security"
on: # yamllint disable-line rule:truthy
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@802f3b1d00b0ab47c3102b4f4ebd866b9f7f8fcf" # v18.0.3
        with:
            branch: "main"
            publish_results: true
