name: "Scorecards supply-chain security"
on: # yamllint disable-line rule:truthy
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@52ac50a94d1eb79f1f13a11d595a585ead491cc2" # v23.0.7
        with:
            branch: "main"
            publish_results: true
