name: "Scorecards supply-chain security"
on: # yamllint disable-line rule:truthy
    branch_protection_rule: ~
    schedule:
        - cron: "37 14 * * 6"
    push:
        branches: ["main"]
permissions: {}
jobs:
    scorecards:
        permissions:
            security-events: "write"
            id-token: "write"
            actions: "read"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/scorecards.yml@d403f72a96c4b04c3d93ff1199c0787d544cd000" # v22.0.6
        with:
            branch: "main"
            publish_results: true
