name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@d403f72a96c4b04c3d93ff1199c0787d544cd000" # v22.0.6 # main
        with:
            target-repo: "anolilab/resume"
