name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@a53f7a16f5a2746f28e5407e85ed093103a15aba" # main
        with:
            target-repo: "anolilab/resume"
