name: "Label Idle Issues"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 0 * * *"

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/stale-issues.yml@52ac50a94d1eb79f1f13a11d595a585ead491cc2" # v23.0.7 # main
        with:
            target-repo: "anolilab/resume"
