name: "Tests"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    test:
        permissions:
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/test.yml@802f3b1d00b0ab47c3102b4f4ebd866b9f7f8fcf" # v18.0.3
        with:
            node_versions: "[\"22\", \"24\"]"
            os_matrix: "[\"ubuntu-latest\"]"
            extra_includes: "[]"
            test_command: "pnpm run test:coverage"
            coverage: false
