# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Test"

on: # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

jobs:
    test:
        strategy:
            matrix:
                os: ["ubuntu-latest"]
                node_version: ["20", "21"]
                include:
                    - os: "macos-latest"
                      node_version: "20"
                    - os: "windows-latest"
                      node_version: "20"
            fail-fast: false

        name: "Build & Unit Test: node-${{ matrix.node_version }}, ${{ matrix.os }}"

        runs-on: "${{ matrix.os }}"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a" # v2.13.1
              with:
                  egress-policy: audit

            - name: "Git checkout"
              uses: "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955" # v4.3.0
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup resources and environment"
              id: "setup"
              uses: "anolilab/workflows/step/setup@main"
              with:
                  node-version: "${{ matrix.node_version }}.x"
                  cache-prefix: "test"

            - name: "test and coverage"
              run: "pnpm run test:coverage"
