# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Test"

on: # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

jobs:
    test:
        name: "Build & Unit Test: node-22, ubuntu-latest"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40" # v2.19.0
              with:
                  egress-policy: "audit"

            - name: "Git checkout"
              uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Setup resources and environment"
              id: "setup"
              uses: "anolilab/workflows/step/setup@5b10e6a2e712406be0b8317df4d437c69b1221ad" # main
              with:
                  node-version: "22.x"
                  cache-prefix: "test"

            - name: "test and coverage"
              run: "pnpm run test:coverage"
