name: "Zizmor"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@0a43f1373be806fe25f390a7119dfd7292c6850f" # v18.0.2
        with:
            min_severity: "medium"
