name: "Zizmor"
on: # yamllint disable-line rule:truthy
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions: {}
jobs:
    zizmor:
        permissions:
            security-events: "write"
            contents: "read"
        uses: "anolilab/workflows/.github/workflows/zizmor.yml@13fa35fefde7f2ad64dbaa108f6421ae3062d711" # v18.0.4
        with:
            min_severity: "medium"
